language: generic 
sudo: require
services:
    - docker

before_install:
    - docker build -t idlikesometea/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true idlikesometea/docker-react npm run test