language: generic 
sudo: require
services:
    - docker

before_install:
    - docker build -t idlikesometea/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true idlikesometea/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-708022934600"
    bucket_path: "docker-react"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
on:
    branch: master